---@class Beast.Icon
local M = {
	beast = {
		vim = "",
		nvim = "",
	},
	diagnostics = {
		error = "",
		warn = "",
		hint = "",
		info = "",
		debug = " ",
		trace = " ",
	},
	git = {
		conflict = "",
		deleted = "",
		added = "",
		renamed = "➜",
		modified = "",
		untracked = "",
		ignored = "󱈸",
	},
	gitsigns = {
		add = "│",
		change = "┊",
		delete = "",
		topdelete = "",
		changedelete = "│",
		untracked = "│",
	},
	kinds = {
		Array = "",
		Boolean = "",
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Copilot = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "",
		Function = "",
		Interface = "",
		Key = "",
		Keyword = "",
		Method = "",
		Module = "",
		Namespace = "",
		Null = "",
		Number = "",
		Object = "",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "",
		Snippet = "",
		String = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
		Macro = "", -- Macro
	},
	brain = {
		codeium = "󰘦 ",
		copilot = " ",
		supermaven = " ",
	},
}

M.colors = {
	brain = {
		codeium = "#09B6A2",
		copilot = "#FEFFFF",
		supermaven = "#6CC644",
	},
}

return M
